### ISSUE TITLE
Offline data base possible ?

### ISSUE THREAD

**Issue by intika** [microg/IchnaeaNlpBackend#18]
Hello 

First thanks for your amazing work !!! 

I found that only official backend are working (from microg) all other alternatives does not seems to work. 

Any way is it possible to use/create an offline data base like "LocalGsmNlpBackend" is supposed to do ? 

Thanks

**Comment by rerbin** [comment]
Online data can ensure data is up to date at any time，Offline data can't ensure this

**Comment by KAMiKAZOW** [comment]
Mozilla's database is proprietary. It cannot be downloaded. So no, it's not possible with this back-end.

Get https://f-droid.org/repository/browse/?fdid=org.openbmap.unifiedNlp
It has the option to download an offline database. Use https://f-droid.org/repository/browse/?fdfilter=radiobeacon&fdid=org.openbmap to scan and contribute WiFi data.

**Comment by rugk** [comment]
> Mozilla's database is proprietary. It cannot be downloaded.

That's wrong. The cell database is public domain and of course [downloadable] (https://location.services.mozilla.com/downloads). Only the Wi-Fi database is not downloadable for privacy reasons.

[This] (https://f-droid.org/repository/browse/?fdfilter=nlp&fdid=org.fitchfamily.android.gsmlocation) backend allows you to download MLS cell database and use it offline.

**Comment by KAMiKAZOW** [comment]
Yes, the GSM database is downloadable. But since it covers only cell towers, it's can also only offer very inaccurate location data. I understood the question as being about the whole database, not just the cell towers, considering it already mentioned LocalGsmNlpBackend.

This is not the place to discuss the reasons why Mozilla does not make the WiFi DB available. Fact is they don't do it, whereas Openbmap and OpenWiFi.su (aka OpenWLANMap) do and of those two only Openbmap has an actively developed NLP back-end.

**Comment by rugk** [comment]
> This is not the place to discuss the reasons why Mozilla does not make the WiFi DB available.

Exactly. I also prefer to stay to the matter of fact way.
I just wanted to correct the claim the database would be proprietary.

And for the TS I think the best way would be to use the other backend.
