### ISSUE TITLE
Does it interfer with MozStumbler

### ISSUE THREAD

**Issue by BridouZ** [microg/IchnaeaNlpBackend#5]
Hello, I've been using your backend for a week now and I have a question:
- I've been using Mozstumbler to help Mozilla Location Service and now that I use your backend I wonder it simply does the same thing  as Mozstumbler does ?
- If it does I can uninstall Mozstumbler because it would be pointless to have it if your backend does the same job isn't it ?

Thanks

**Comment by Djfe** [comment]
I guess it doesn't use the same backend/it works differently.
But it should work.

Maybe the devs could use the libstumbler though:
https://github.com/mozilla/MozStumbler/wiki/libstumbler-design-doc

garvankeeley and crankycoder separated the stumbling backend and the GUI completely now, so that you can put the stumbler as a lib into your apps

if they would use libstumbler, then this could probably work in the same way (->you could uninstall MozStumbler then), but I'm not sure if you want to have full scanning turned on in the background all-the-time (powerconsuming)

**Comment by mar-v-in** [comment]
The Ichnaea backend does not use libstumbler as it's not the primary idea to contribute data, but to use it. If contribution is enabled in Ichnaea Backend, this will be completely passive, meaning only if GPS location is available (due to usage by another app) it will be added to the request to Mozilla servers that is send to geolocate.
MozStumbler is an active client, meaning it actively uses the GPS and regularly sends data to the server without any other purpose then contributing.

Both have different tasks, but opening a actively scanning app (eg. OsmAnd) will cause the Ichnaea Backend to contribute mostly the same as MozStumbler does. However MozStumbler is more efficient in doing so. Finally I'd suggest you to disable the Ichnaea backend (or at least the contribution option in it) while running MozStumber, as it will cause the same data to be send twice, which will decrease the quality of the Mozilla database and cause unnecessary traffic.
